config/routes.rb
Dealplat::Application.routes.draw do

  devise_for :users

  resources :markers
  root 'welcome#index'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    can :manage, :all

    can :manage, Marker, :user_id => user.id

  end

end

app/models/base/model.rb
class Base::Model < ActiveRecord::Base
  self.abstract_class = true
  NAMES_LENGTH = 1...100

  #BASE_MODEL_CHILDREN_NAMES = %w(UserGeneratedContentModel SeedableModel VersionableModel)
  #def self.inherited(child_class)
  #  super
  #  unless BASE_MODEL_CHILDREN_NAMES.include?(child_class.name) || (child_class.ancestors.map(&:name) & BASE_MODEL_CHILDREN_NAMES).any?
  #    raise "#{child_class.name} mistakenly inherits from BaseAbstractModel - use one of BaseAbstractModel child classes as parent for #{child_class.name}\n"
  #  end
  #end

  class << self

    def cache_enabled?
      Rails.cache.stats.present?
    end

    def cached_all(params = {})
      self.cached_block_by_key(params[:key] || "#{self.name}.all") { all.to_a }
    end

    def cached_block_by_key(key)
      if cache_enabled?
        Rails.cache.fetch(key) do
          yield
        end
      else
        yield
      end
    end

    def random_record
      self.order("RAND()").first
    end

    def random_record_id
      self.random_record.try(:id)
    end

  end

end

app/models/base/seed_model.rb
# might have special behavior in future; for the moment it's just convenient to track seedable models separately
class Base::SeedModel < Base::Model
  self.abstract_class = true

  class << self

    def seedable_models
      @seedable_models ||= descendants.select { |child| !child.abstract_class }
    end
    alias :models :seedable_models

    def seedable_tables
      @seedable_tables ||= seedable_models.map(&:table_name)
    end
    alias :tables :seedable_tables

  end

end

app/models/base/user_generated_content_model.rb
# non-seedable, non-versionable model
class Base::UserGeneratedContentModel < Base::Model
  self.abstract_class = true

  class << self

    def ugc_models
      @ugc_models ||= descendants.select { |child| !child.abstract_class }
    end
    alias :models :ugc_models

  end

end

app/models/base/version_model.rb
class Base::VersionModel < Base::UserGeneratedContentModel
  self.abstract_class = true

  class << self
    #TODO: implement PaperTrail if will need

    def versionable_models
      @versionable_models ||= descendants.select { |child| !child.abstract_class }
    end
    alias :models :versionable_models

  end

end

app/models/marker.rb
class Marker < Base::VersionModel

  belongs_to :user
  belongs_to :marker_category, :class_name => 'Marker::Category'

end

app/models/marker/category.rb
class Marker::Category < Base::SeedModel
  has_many :markers
end

app/models/user.rb
class User < Base::VersionModel
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :markers

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_action :cancan_params_converter

  def cancan_params_converter
    resource = controller_path.singularize.gsub('/', '_').to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  load_and_authorize_resource

  respond_to :json

  # GET /markers
  # GET /markers.json
  def index
    respond_with @markers
    #respond_with @markers do |format|
    #  format.json { render json: @markers }
    #end
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
    respond_with @marker
  end

  # GET /markers/new
  def new
  end

  # GET /markers/1/edit
  def edit
  end

  # POST /markers
  # POST /markers.json
  def create
    @marker.save
    respond_with @marker do |format|
      format.json { render json: @marker }
    end
  end

  # PATCH/PUT /markers/1
  # PATCH/PUT /markers/1.json
  def update
    @marker.update(marker_params)
    respond_with @marker
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
    @marker.destroy

  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def marker_params
      params.require(:marker).permit(:latitude, :longitude, :marker_category_id, :title)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @marker = Marker.new
    render :layout => "backbone_application", :template => "welcome/map" if user_signed_in?
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dealplat" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true  %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true  %>
  </head>
  <body class="main-bg">

    <div class="container">
        <%= bootstrap_flash %>
        <%= yield %>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/backbone_application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dealplat" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->


    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag 'http://maps.google.com/maps/api/js?sensor=true'  %>
    <%= javascript_include_tag "backbone_application_includes", :media => "all"  %>

    <script>
        Dealplat.app             = new Dealplat.Application;
        Dealplat.app.currentUser = new Dealplat.Models.User(<%= current_user.to_json.html_safe %>);
    </script>

  </head>
  <body>
      <div class="container">
          <div class="container-fluid">
            <div class="row-fluid">

              <div class="span2" id="bb-sidebar">

              </div>

              <div class="span10" id="bb-content-view">

              </div>

            </div>
          </div>
      </div>
      <%= javascript_include_tag "backbone_application",          :media => "all"  %>
  </body>



</html>

app/views/layouts/logged_user.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dealplat" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->


    <%= stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true  %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag 'http://maps.google.com/maps/api/js?sensor=true'  %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true  %>
  </head>
  <body class="main-bg">

    <div class="container">
        <%= bootstrap_flash %>
        <%= yield %>

    </div> <!-- /container -->

  </body>
</html>

app/views/markers/_form.html.erb
<%= simple_form_for(@marker) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/markers/edit.html.erb
<h1>Editing marker</h1>

<%= render 'form' %>

<%= link_to 'Show', @marker %> |
<%= link_to 'Back', markers_path %>

app/views/markers/index.html.erb
<h1>Listing markers</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @markers.each do |marker| %>
      <tr>
        <td><%= link_to 'Show', marker %></td>
        <td><%= link_to 'Edit', edit_marker_path(marker) %></td>
        <td><%= link_to 'Destroy', marker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marker', new_marker_path %>

app/views/markers/new.html.erb
<h1>New marker</h1>

<%= render 'form' %>

<%= link_to 'Back', markers_path %>

app/views/markers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_marker_path(@marker) %> |
<%= link_to 'Back', markers_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div class="center-text">
    <h1>Welcome#index</h1>
    <p>Find me in app/views/welcome/index.html.erb</p>


    <div id="user_nav">
      <% if user_signed_in? %>
          Signed in as <%= current_user.email %>. Not you?
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
          <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
      <% end %>
    </div>
</div>

app/views/welcome/map.html.erb
<div id="map">

</div>

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"></h3>

  </div>

  <div class="modal-body">
    <%= simple_form_for Marker.new do |f|%>
        <%= f.input :title%>
        <%= f.input :marker_category, :collection => Marker::Category.all, :include_blank => false  %>
    <%end%>
  </div>


  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary" id="dermo">Save changes</button>
  </div>
</div>